src/Entity/Ville.php
<?php

namespace App\Entity;

use App\Repository\VilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VilleRepository::class)
 */
class Ville
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=125)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity=Lieu::class, mappedBy="ville", orphanRemoval=true, cascade={"persist"})
     */
    private $lieux;

    public function __construct()
    {
        $this->lieux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Lieu[]
     */
    public function getLieux(): Collection
    {
        return $this->lieux;
    }

    public function addLieux(Lieu $lieux): self
    {
        if (!$this->lieux->contains($lieux)) {
            $this->lieux[] = $lieux;
            $lieux->setVille($this);
        }

        return $this;
    }

    public function removeLieux(Lieu $lieux): self
    {
        if ($this->lieux->removeElement($lieux)) {
            // set the owning side to null (unless already changed)
            if ($lieux->getVille() === $this) {
                $lieux->setVille(null);
            }
        }

        return $this;
    }
}

src/Form/SortieType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\Sortie;
use App\Form\EventListener\AddLieuByVilleSubscriber;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SortieType extends AbstractType
{
    private $addLieuByVilleSubscriber;

    public function __construct(AddLieuByVilleSubscriber $addLieuByVilleSubscriber)
    {
        $this->addLieuByVilleSubscriber = $addLieuByVilleSubscriber;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        ini_set('memory_limit', '1024M');

        $builder
            ->add('nom')
            ->add('dateHeureDebut', DateTimeType::class, ['html5' => true, 'widget' => 'single_text'])
            ->add('duree')
            ->add('dateLimiteInscription', DateType::class, ['html5' => true, 'widget' => 'single_text'])
            ->add('nbInscriptionsMax')
            ->add('infosSortie', TextareaType::class)
            ->add('campus', EntityType::class, [
                'class' => Campus::class,
                'choice_label' => 'nom',
            ]);

        $builder->addEventSubscriber($this->addLieuByVilleSubscriber);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Entity\Sortie;
use App\Form\AnnulSortieType;
use App\Form\SearchType;
use App\Form\SortieType;
use App\Repository\EtatRepository;
use App\Repository\LieuRepository;
use App\Repository\ParticipantRepository;
use App\Repository\SortieRepository;
use App\Service\ClotureSortieService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

class SortieController extends AbstractController
{
    /**
     * @Route("/sortie/create", name="sortie_create")
     */
    public function create(Request $request, EntityManagerInterface $entityManager, ParticipantRepository $participantRepository, EtatRepository $etatRepository): Response
    {
        $sortie = new Sortie();
        $sortieForm = $this->createForm(SortieType::class, $sortie);

        $sortieForm->handleRequest($request);

        if ($sortieForm->isSubmitted() && $sortieForm->isValid()) {
            switch ($sortieForm->getClickedButton()->getName()) {
                case 'save':
                    $libelle = 'Créée';
                    $message = 'sortie créé ! Merci beaucoup.';
                    $nextAction = 'sortie_list';
                    break;
                case 'saveAndPublish':
                    $libelle = 'Ouverte';
                    $message = 'sortie créé et Publiée ! Merci beaucoup.';
                    $nextAction = 'sortie_list';
                    break;
            }

            $email = $this->getUser()->getUsername();
            $participant = $participantRepository->findOneByEmail($email);

            $etat = $etatRepository->findOneBy(['libelle' => $libelle]);
            $sortie->setOrganisateur($participant);
            $sortie->setEtat($etat);
            $entityManager->persist($sortie);
            $entityManager->flush();

            $this->addFlash(
                'success',
                $message
            );

            return $this->redirectToRoute($nextAction);
        }

        return $this->render('sortie/create.html.twig', [
            'sortieForm' => $sortieForm->createView(),
        ]);
    }

    /**
     * @Route("/sorties", name="sortie_list")
     */
    public function list(SortieRepository $sortieRepository,
                         ClotureSortieService $clotureSortieService,
                         Request $request
    ): Response {
        // $series = $sortieRepository->findAll();
        // $series = $sortieRepository->findBy([], ['nom' => 'DESC', 'dateLimiteInscription' => 'DESC'], 30);
        // $sorties = $sortieRepository->findSorties();
        $sorties = $sortieRepository->findAll();
        $sorties = $clotureSortieService->updateEtatByDateSortie((array) $sorties);
        //  $sorties = $clotureSortieService->sortiesToDisplay($sorties);

        $data = new SearchData();
        $searchForm = $this->createForm(SearchType::class, $data);
        $searchForm->handleRequest($request);

        $sorties = $sortieRepository->findSearch($data);

        // Appel une service de changement d'etat des sorties

        return $this->render('sortie/list.html.twig', [
            'sorties' => $sorties,
            'searchForm' => $searchForm->createView(),
        ]);
    }

    /**
     * @Route("/sortie/details/{id}", name="sortie_details")
     */
    public function details(SortieRepository $sortieRepository, int $id): Response
    {
        $sortie = $sortieRepository->find($id);

        if (!$sortie) {
            throw $this->createNotFoundException('Sortie non trouvée !');
        }

        return $this->render('sortie/details.html.twig', ['sortie' => $sortie]);
    }

    /**
     * @Route("/sortie/inscription/{id}", name="sortie_inscription")
     */
    public function inscription(EntityManagerInterface $entityManager, SortieRepository $sortieRepository, ParticipantRepository $participantRepository, int $id): Response
    {
        $sortie = $sortieRepository->find($id);

        $email = $this->getUser()->getUsername();
        $participant = $participantRepository->findOneByEmail($email);

        if (!$sortie) {
            throw $this->createNotFoundException('Sortie non trouvée !');
        }

        $sortie->addParticipant($participant);

        $entityManager->persist($sortie);
        $entityManager->flush();

        $this->addFlash(
                'success',
                'Vous été bien enregistre dans la sortie ! Merci beaucoup.'
            );

        return $this->render('sortie/details.html.twig', ['sortie' => $sortie]);
    }

    /**
     * @Route("/sortie/desister/{id}", name="sortie_desister")
     */
    public function desister(EntityManagerInterface $entityManager, SortieRepository $sortieRepository, ParticipantRepository $participantRepository, int $id): Response
    {
        $sortie = $sortieRepository->find($id);
        $email = $this->getUser()->getUsername();

        $participant = $participantRepository->findOneByEmail($email);

        if (!$sortie) {
            throw $this->createNotFoundException('Sortie non trouvée !');
        }

        $sortie->removeParticipant($participant);

        $entityManager->persist($sortie);
        $entityManager->flush();

        $this->addFlash(
                'success',
                'Vous été bien desisncrit de la sortie ! Merci beaucoup.'
            );

        return $this->render('sortie/details.html.twig', ['sortie' => $sortie]);
    }

    /**
     * @Route("/sortie/publier/{id}", name="sortie_publier")
     */
    public function publier(EntityManagerInterface $entityManager, SortieRepository $sortieRepository, EtatRepository $etatRepository, ParticipantRepository $participantRepository, int $id, AuthorizationCheckerInterface $authorizationChecker): Response
    {
        $sortie = $sortieRepository->find($id);

        $email = $this->getUser()->getUsername();

        $organisateur = $participantRepository->findOneByEmail($email);

        $this->denyAccessUnlessGranted('sortie_publier', $sortie);

        if (!$sortie) {
            throw $this->createNotFoundException('Sortie non trouvée !');
        } elseif ($sortie->getOrganisateur() !== $organisateur) {
            throw $this->createNotFoundException('Vous n\'aves pas les droit de publier cette sortie !');
        }

        $etat = $etatRepository->findOneBy(['libelle' => 'Ouverte']);

        $sortie->setEtat($etat);

        $entityManager->persist($sortie);
        $entityManager->flush();

        $this->addFlash(
                        'success',
                        'Vous aves bien publie la sortie ! Merci beaucoup.'
                    );

        return $this->render('sortie/details.html.twig', ['sortie' => $sortie]);
    }

    /**
     * @Route("/annule/{id}", name="sortie_annuler")
     *
     * @param $entityManager
     *
     * @return Response
     */
    public function annule(int $id,
                           SortieRepository $sortieRepository,
                           Request $request,
                           EntityManagerInterface $entityManager,
                           EtatRepository $etatRepository
    ): Response {
        $sortie = $sortieRepository->findOneBySomeField($id);

        $annulForm = $this->createForm(AnnulSortieType::class, $sortie);

        //traitement du formulaire
        $annulForm->handleRequest($request);

        if ($annulForm->isSubmitted()) {
            $etat = $etatRepository->findOneBy(['libelle' => 'Annulée']);
            $sortie->setEtat($etat);
            //message flash pour annoncer la bonne exécution de l'annulation
            $this->addFlash('success', 'la sortie a été annulée');

            //envoi des données à la BD pour modifier le champs infosSortie
            $entityManager->persist($sortie);
            $entityManager->flush();

            //redirection vers la page d'accueil
            return $this->redirectToRoute('sortie_list');
        }

        return $this->render('sortie/annule.html.twig', [
            'sortie' => $sortie,
            'annulForm' => $annulForm->createView(),
        ]);
    }

    /**
     * Returns a JSON string with the lieus of the Ville with the providen id.
     *
     * @Route("/sortie/lieux-ville", name="sortie_lieux_ville")
     *
     * @return JsonResponse
     */
    public function listeLieuxByVilleAction(Request $request, LieuRepository $lieuRepository)
    {
        // Rechercher les lieux qui appartiennent à la ville avec l’id donné comme paramètre GET "ville_id"
        $villeId = $request->query->get('ville_id');

        $lieux = $lieuRepository->findById($villeId);

        // Serialize into an array the data that we need, in this case only name and id
        // Note: you can use a serializer as well, for explanation purposes, we'll do it manually
        $responseArray = [];
        foreach ($lieux as $lieu) {
            $responseArray[] = [
                'id' => $lieu->getId(),
                'nom' => $lieu->getNom(),
                'rue' => $lieu->getRue(),
                'latitude' => $lieu->getLatitude(),
                'longitude' => $lieu->getLongitude(),
                'code_postal' => $lieu->getVille()->getCodePostal(),
            ];
        }

        // Return array with structure of the lieu of the providen city id
        return new JsonResponse($responseArray);
    }
}

templates/sortie/annule.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-9  col-lg-10 mx-auto">
            <div id="sortie-card" class=" border-0 shadow rounded-3 my-5 ">
                <div class="card-body p-4 p-sm-5">
                    <h3 class="card-title text-center mb-5 fw-bold fs-3" style="color: #0d6efd" >Annuler une sortie</h3>
                    <table class="table table-hover">

                        <tbody>
                        <tr class="table-primary">
                            <th scope="row">Nom de la sortie :</th>
                            <td>{{ sortie.nom }}</td>
                         </tr>
                        <tr class="table-secondary">
                            <th scope="row">Date de la sortie :</th>
                            <td>{{ sortie.dateHeureDebut | date("d/m/Y") }}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row">Campus : </th>
                            <td>{{ sortie.campus.nom }}</td>
                        </tr>
                        <tr class="table-info">
                            <th scope="row">Lieu : </th>
                            <td>{{ sortie.lieu.nom }} {{ sortie.lieu.rue }} {{ sortie.lieu.ville.codePostal}} {{ sortie.lieu.ville.nom}}</td>
                        </tr>
                        <tr class="table-light">
                            <th scope="row">Motif de l'annulation :  </th>
                            <td>
                            {{ form_start(annulForm) }}
                            {{ form_widget(annulForm.infosSortie) }}
                            </td>
                        </tr>
                        <tr>
                        <th scope="row"> </th>
                        <td>
                            <button type="submit" id="enregistrer" class="btn btn-primary btn-lg">Enregistrer</button> &nbsp;
                            <button type="reset" id="annuler" class="btn btn-primary btn-lg">Annuler</button>
                            </td>
                            {{ form_end(annulForm)}}

                        </tr>
                        </tbody>
                    </table>





                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block title %}

{% endblock %}

templates/sortie/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create une nouvelle Sortie !{% endblock %}

{% block body %}

    <div class="container">
        <div id="sortie-card" class=" border-0 shadow rounded-3 my-3 ">
            <div class="card-body p-4 p-sm-3">

                <!-- titre du formulaire-->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-header bg-primary" style="text-align: center">
                            <h1>Créer une sortie</h1>
                        </div>
                    </div>
                </div>


                <div class="row p-sm-3">

                    <!-- partie gauche du formulaire-->
                    <div class="col-lg-6">
                        <div class="bs-component">
                            <table class="table">
                                <tr class="table">
                                    {{ form_start(sortieForm) }}
                                    <th scope="row">Nom de la sortie :  </th>
                                    <td>
                                        {{ form_widget(sortieForm.nom) }}
                                    </td>
                                </tr>

                                <tr class="table">
                                    <th scope="row">Date et heure de la sortie :  </th>
                                    <td>
                                        {{ form_widget(sortieForm.dateHeureDebut) }}
                                        {{ form_errors(sortieForm.dateHeureDebut) }}
                                    </td>
                                </tr>

                                <tr class="table">
                                    <th scope="row">Date limite d'inscription :  </th>
                                    <td>
                                        {{ form_widget(sortieForm.dateLimiteInscription) }}
                                    </td>
                                </tr>

                                <tr class="table">
                                    <th scope="row">Nombre de places :  </th>
                                    <td>
                                        {{ form_widget(sortieForm.nbInscriptionsMax) }}
                                    </td>
                                </tr>

                                <tr class="table">
                                    <th scope="row">Durée :  </th>
                                    <td>
                                        {{ form_widget(sortieForm.duree) }}
                                    </td>
                                </tr>

                                <tr class="table">
                                    <th scope="row">Description et infos :  </th>
                                    <td>
                                        {{ form_widget(sortieForm.infosSortie) }}
                                    </td>
                                </tr>

                            </table>
                        </div>
                    </div>


                    <!--partie de droite du formulaire-->

                    <div class="col-lg-4 offset-lg-1">

                        <table class="table">
                            <tbody>

                            <tr class="table">
                                <th scope="row">Campus :  </th>
                                <td>
                                    {{ form_widget(sortieForm.campus) }}
                                </td>
                            </tr>

                            <tr class="table">
                                <th scope="row">Ville :  </th>
                                <td>
                                    {{ form_widget(sortieForm.ville) }}
                                </td>
                            </tr>

                            <tr class="table">
                                <th scope="row">lieu :  </th>
                                <td>
                                    {{ form_widget(sortieForm.lieu) }}
                                </td>
                            </tr>

                            <tr class="table">
                                <th scope="row">Rue :  </th>
                                <td id="rue">
                                </td>
                            </tr>

                            <tr class="table">
                                <th scope="row">Code Postal :  </th>
                                <td id="cp">
                                </td>
                            </tr>

                            <tr class="table">
                                <th scope="row">Latitude :  </th>
                                <td id="latitude">
                                </td>
                            </tr>

                            <tr class="table">
                                <th scope="row">Longitude :  </th>
                                <td id="longitude">
                                </td>
                            </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- le partie boutons-->

                <div class="col-lg-12 text-center">

                    {{ form_widget(sortieForm.save)}} &nbsp;
                    {{ form_widget(sortieForm.saveAndPublish)}} &nbsp;
                    <a href="{{ path('sortie_list') }}" class="btn btn-primary btn-lg" title="Annuler">Annuler</a>
                </div>

                {{ form_end(sortieForm) }}
            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>
    var $ville = $('#sortie_ville');
    var arrayLieuId = [];

    // When ville gets selected ...
    $ville.change(function () {
        var sortieLieu = $(this);
        villeId = sortieLieu.val()
        // ... retrieve the corresponding form.
        var $form = $(this).closest('form');
        // Simulate form data, but only include the selected ville value.
        var data = {};
        data[$ville.attr('name')] = $ville.val();
        // Submit data via AJAX to the form's action path.
        $.ajax({
            url: "{{ path('sortie_lieux_ville') }}",
            type: "GET",
            dataType: "JSON",
            data: {
                ville_id: villeId
            },
            success: function (lieux) {
                $('#sortie_lieu').on('change', function () {
                    inputSortieSelectedRue = $("#rue");
                    inputSortieSelectedCp = $("#cp");
                    inputSortieSelectedLatitude = $("#latitude");
                    inputSortieSelectedLongitude = $("#longitude");
                    // Empty input
                    inputSortieSelectedRue.html('');
                    inputSortieSelectedCp.html('');
                    inputSortieSelectedLatitude.html('');
                    inputSortieSelectedLongitude.html('');
                    // get value id lieu selected and use for acces to lieu of liex array and get data
                    var lieuSelectedId = lieuSelect.find("option:selected").val();

                    inputSortieSelectedRue.append('<input type="text" name="rue" value="' + lieux[arrayLieuId[lieuSelectedId]].rue + '" />');
                    inputSortieSelectedLatitude.append('<input type="text" name="latitude" value="' + lieux[arrayLieuId[lieuSelectedId]].latitude + '" />');
                    inputSortieSelectedLongitude.append('<input type="text" name="longitude" value="' + lieux[arrayLieuId[lieuSelectedId]].longitude + '" />');
                    inputSortieSelectedCp.append('<input type="text" name="code_postal" value="' + lieux[arrayLieuId[lieuSelectedId]].code_postal + '" />');
                });

                var lieuSelect = $("#sortie_lieu");

                var inputfieldLieu =  $("#sortie_lieu");
                // Remove current options
                lieuSelect.html('');

                // Empty value ...
                lieuSelect.append('<option value> Select a lieu de ' + sortieLieu.find("option:selected").text() + ' ...</option>');

                $.each(lieux, function (key, lieu) {
                    // Save the position of lieu in to the array of lieux with the key lieu.id
                    arrayLieuId[lieu.id] = key;
                    lieuSelect.append('<option value="' + lieu.id + '">' + lieu.nom + '</option>');
                });
            },
            error: function (err) {
                alert("Un erreur s'est produit lors du chargement des données ...");
            }
        });
    });
</script>

{% endblock %}

templates/sortie/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aficher une sortie ! | {{ parent() }} {% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
            <div id="detail-sortie-card" class=" border-0 shadow rounded-3 my-5 ">
                <div class="card-body p-4 p-sm-5">
                    <div class="row">
                        <div class="col">
                            <h5>Nom de la sortie :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.nom }}
                        </div>
                        <div class="col">
                            <h5>Campus :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.campus.nom }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <h5>Date et Heure de la Sortie :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.dateHeureDebut|date('d/m/Y') }}
                        </div>
                        <div class="col">
                            <h5>Lieu :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.lieu.nom }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <h5>Date limite d'inscription :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.dateLimiteInscription|date('d/m/Y') }}
                        </div>
                        <div class="col">
                            <h5>Rue :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.lieu.rue }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <h5>Nombre de places :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.nbInscriptionsMax }}
                        </div>
                        <div class="col">
                            <h5>Code Postal :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.lieu.ville.codePostal }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <h5>Durée :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.duree }} minutes
                        </div>
                        <div class="col">
                            <h5>Latitude :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.lieu.latitude }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <h5>Description et infos :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.infosSortie }} minutes
                        </div>
                        <div class="col">
                            <h5>Longitude :</h5>
                        </div>
                        <div class="col">
                            {{ sortie.lieu.longitude }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="list-sorties-card" class="p-5">
    <h2>Liste des participants inscrits :</h2>
    <table class="table table-responsive">
        <tr>
            <th>Pseudo</th>
            <th>Nom</th>
        </tr>
        {% for participant in sortie.participants %}
        <tr>
            <td><a href="{{ path('profile_display', {'pseudo': participant.pseudo}) }}" title="Profile">{{ participant.pseudo }}</a></td>
            <td>{{ participant.nom }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}